import type { Metadata } from "next";
import "./globals.css";
import PrlxProvider from "@/Providers/PrlxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/logo.svg" sizes="any" />
      <title>Danila Mandrabura</title>
      <body>
        <PrlxProvider>{children}</PrlxProvider>
      </body>
    </html>
  );
}
