// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact_me: dynamic(() => import("./ContactMe")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  parallax: dynamic(() => import("./Parallax")),
  portfolio: dynamic(() => import("./Portfolio")),
  skills: dynamic(() => import("./Skills")),
};
